### PR TITLE
NPA complete refactor

### PR DESCRIPTION
**Pull request by TheTechRobo**
_No description provided._

### CODE REVIEW

**Comment by TheTechRobo** [comment]
@TheRuntingMuumuu PLEASE next time if i make a branch to rewrite a page, use it if you want to change it!

**Comment by owendaigle** [comment]
I thought that since they were small changes they should work, but that is what I'll do in the future

**Comment by TheTechRobo** [comment]
fixed conflicts.

**Comment by TheTechRobo** [comment]
TRM suggested to merge it into beta1 as 80% complete.

**Pull request merged**
