### PR TITLE
Update changelog.txt and trmSiteChangelog.docx

### PR DESCRIPTION
**Pull request by TheTechRobo**
- Organisation
- Some English fixes.
- Update changelog.txt to be more modern.

### CODE REVIEW

**Comment by TheTechRobo** [comment]
Please approve this pull request or suggest changes, but do not merge it. To keep the git history clean, I'll squash and merge.

**Comment by owendaigle** [comment]
I think the txt one looks better, I do not really maintain that one since it is easier to work with the docx file for me.

**Comment by TheTechRobo** [comment]
@TheRuntingMuumuu Do you approve this PR?

**Comment by owendaigle** [comment]
I think I approve?? What is a pull request?? Do I have to do something to approve it?

**Comment by TheTechRobo** [comment]
@TheRuntingMuumuu You don't really have to do anything special, I was just making sure you were OK with the changes.

This is a pull request.

**Comment by TheTechRobo** [comment]
In theory, next time you could go  into the "files changed" and submit an approving review or requesting changes, but you don't ahve to.

**Pull request merged**
